### ISSUE TITLE
Validator fails with UTF-8 characters?

### ISSUE THREAD

**Issue by smrgeoinfo** [usgs/gems-tools-arcmap#15]
Error message when validating a new GEMS database imported from shapefiles: 
    mu = str(row.getValue('MapUnit'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xba' in position 1: ordinal not in range(128)

validating database with special characters for MapUnit; not clear if hanging in introspection of DMU or the GeoPolys feature class. suspect  Map unit string in question is 'Mº' could be 'P³'?  There is no ..ba in the MapUnit polys or DMU.

I can provide the geodatabase if that's useful?

**Comment by smrgeoinfo** [comment]
when I took the unit id's with the special characters (cambrian and Penn-Perm  ligatures) out, the validation worked

**Comment by rhaugerud** [comment]
How did you get the special characters into the DMU table?
