### ISSUE TITLE
Switch to Python 3?

### ISSUE THREAD

**Issue by BenjiDa** [usgs/gems-tools-arcmap#25]
Any reason we shouldn't be writing this in Python 3 considering Python 2.7 end of life is near?

**Comment by ethoms-usgs** [comment]
Ben,
First, I apologize for the delay in answering. We don't always monitor the repo issues like we should. 

I don't use ArcGIS Pro much so by default I'm always working against 2.7 but I will look into porting the tools to 3. It looks like changes can be almost completely automated.

Do you mostly use ArcMap or ArcGIS Pro? I don't have any knowledge of which one most geologic mappers use.

**Comment by freewheelCarto** [comment]
We definitely should be working toward a suite of tools for Pro / python 3. Eventually it will be necessary as both arcmap and python 2 lose support. I don’t think it needs to be immediate, but may as well start on it. 

My guess is much of the python translation could be automated, but I think the Arcpy functions might require more hands on work. 

-Tanner

**Comment by ethoms-usgs** [comment]
Closing this old issue. 
Version 2 of the toolbox in Python 3 is at https://github.com/usgs/gems-tools-pro.
