### ISSUE TITLE
Version of tools for ArcGIS Pro 2

### ISSUE THREAD

**Issue by ethoms-usgs** [usgs/gems-tools-arcmap#34]
I have completed a first pass on updating all of the tools to Python 3 for use in ArcGIS Pro 2. The latest version is at my fork of the repo: 
https://github.com/ethoms-usgs/GeMS_Tools

For this version and versions that work with ArcMap 10, I created release tags using [semantic versioning](https://semver.org/).

I have not created a pull request to merge this repo with my latest repo because I don't know how that will affect the master. I will get some help on that, but in the meantime, go over to my repo, take a look, and let me know what you think.

**Comment by ethoms-usgs** [comment]
I should add that Eric Martinez (USGS git guru) told me:

> If this source code is official USGS source code (e.g. it gets used in USGS processes, generating data, etc...) then you should really migrate it to code.usgs.gov. This is publicly accessible and can be mirrored back to the existing GitHub project if you want to keep it available there as well. I can certainly help with details on this if you're interested.

**Comment by rbeard09** [comment]
I am running through some of the tools you did for ArcPro and I keep having the Create Geodatabase fail with the following message: 

Traceback (most recent call last):

  File "C:\Users\___removed_____\___Removed_________\Desktop\temp\GeMS_Tools-master\Scripts\GeMS_CreateDatabase_AGP2.py", line 427, in <module>
    main(thisDB,coordSystem,nCrossSections)
  File "C:\Users\____Removed_____\Desktop\temp\GeMS_Tools-master\Scripts\GeMS_CreateDatabase_AGP2.py", line 253, in main
    arcpy.Copy_management(os.path.dirname(sys.argv[0])+'/../Resources/GeMS_lib.gdb/GeoMaterialDict', thisDB+'/GeoMaterialDict')
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 5002, in Copy
    raise e
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 4999, in Copy
    retval = convertArcObjectToPythonObject(gp.Copy_management(*gp_fixargs((in_data, out_data, data_type, associated_data), True)))
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
 ERROR 000732: Input Data: Dataset C:\Users\_____Removed_____\____Removed_____\Desktop\temp\GeMS_Tools-master\Scripts/../Resources/GeMS_lib.gdb/GeoMaterialDict does not exist or is not supported
Failed to execute (Copy).
 Failed to execute (CreateDatabase).



-Let me know your thoughts. 
Thank you for what you do with these tools.

**Comment by ethoms-usgs** [comment]
Hi rbeard09, 
Thank you for finding that problem, Apparently, I lost track of GeMS_lib.gdb, which didn't get copied to the \Resources folder in my repo. I can't update the repo right now, so the workaround I suggest is to download the entire USGS ArcMap repo (https://github.com/usgs/GeMS_Tools), and move GeMS_lib.gdb from the \Resources folder of that toolbox to the \Resources folder where you have my upgraded version ArcGIS Pro version installed. If you still get an error, please start an issue at my repo (https://github.com/ethoms-usgs/GeMS_Tools), not in response to this comment.
Thanks!

**Comment by ethoms-usgs** [comment]
It's been a while since this issue was raised and the tools have changed a lot. I am closing it.
