### ISSUE TITLE
incorrect link on a wiki page

### ISSUE THREAD

**Issue by cmrRose** [usgs/gems-tools-arcmap#42]
On the wiki page https://github.com/usgs/gems-tools-arcmap/wiki/CompleteMetadata, the link at the bottom of the page _should_ be [http://ngmdb.usgs.gov/Info/standards/GeMS](http://ngmdb.usgs.gov/Info/standards/GeMS) -- it is currently missing ".usgs" in the URL.

**Comment by ethoms-usgs** [comment]
Done. Thanks, Caroline!
