### ISSUE TITLE
Set ID Values - MapUnitPoly_ID sets to X3X00001....

### ISSUE THREAD

**Issue by stub0035** [usgs/gems-tools-arcmap#43]
When running the Set ID value tool all my ID's populate correctly except for the MapUnitPolys_ID.  In stead of values of MUP00001.... I receive X3X00001.  

Any thoughts with this?
![MapUnitPoly](https://user-images.githubusercontent.com/8901908/74186890-16450b00-4c11-11ea-8d24-807cb16aa019.PNG)

**Comment by ethoms-usgs** [comment]
Wow! Interesting. It just happened to me too with a demo database. I am looking into it.

**Comment by stub0035** [comment]
Awesome! Thank you!!
-- 
Jacqueline D. Hamilton PG,GISP
Geologic Information Scientist |Minnesota Geological Survey | mngs.umn.edu
2609 Territorial Rd., St. Paul 5514
University of Minnesota | umn.edu
stub0035@umn.edu | 612-626-8292

**Comment by ethoms-usgs** [comment]
Jacque, 
I believe I have fixed this; it now works for me. Please try out the new script and let me know.

**Comment by stub0035** [comment]
Thank you Evan,
I made the change to the script as you suggested and it worked beautifully. Thank you!

**Comment by ethoms-usgs** [comment]
Thanks for letting me know, Jacque. I will close the issue
