### ISSUE TITLE
Validation tool flagging errors incorrectly

### ISSUE THREAD

**Issue by LLeBlanc110** [usgs/gems-tools-arcmap#47]
I ran the validation tool and had a Level 2 compliant GDB, with errors flagged for having glossary terms that were not used in the database. I deleted the two Glossary definitions that weren't used in the GDB (questionable, and geomaterial-low), and when I ran the validation tool again it flagged all these errors and suddenly the GDB was Level 1 compliant. The error report listed all these type values as not being defined, and missing data sources - errors which were not errors prior to deleting these values. I re-ran the tool a few times in ArcMap and was still getting these wild errors, ones that I knew were not actually errors. So, I ran the validation tool in ArcCatalog and the GDB had no errors and was Level 3 compliant. I unfortunately didn't save any of the error reports from when this was happening. I've attached the message and environments from the results of the validation tool.
[ValidationMessage.txt](https://github.com/usgs/gems-tools-arcmap/files/4866455/ValidationMessage.txt)
![ValidationEnvironments](https://user-images.githubusercontent.com/61474179/86405574-35ebd700-bc77-11ea-9a59-96431e9635f3.JPG)

**Comment by rhaugerud** [comment]
In my experience, errors like this reflect the presence of a join or a definition query. Or the presence (in ArcMap) of a map-composition layer that Arc wrongly identifies as part the database being validated--hence the advice to run from ArcCatalog.  I don't understand ArcMap well enough to code a test for this latter possibility.  I have modified the help text for the script to emphasize these causes of incorrectly-flagged errors.

I'm closing this issue, but if you'd like to see it re-opened, and especially if you have ideas about how to better address it, I'd be happy to revisit.

Ralph

**Comment by LindaTedrow** [comment]
I have run into this same issue but have never run from ArcMap.  Also do not have joins in my glossary.
Linda

**Comment by rhaugerud** [comment]
Linda-

Do you have any idea as to the triggering phenoma?

Ralph
________________________________

**Comment by LindaTedrow** [comment]
Ralph,
I don’t know why this happens – but generally what happens is the values do not show up.
Then I add again and then I have two values.

For some reason ArcCatalog mostly does not look like it updates; but it does.
I blamed our server system but if others are having this same problem it is not “our server”.

Linda
