### ISSUE TITLE
Validate Database tool crashes

### ISSUE THREAD

**Issue by tfelger** [usgs/gems-tools-arcmap#48]
The Validate Database tool crashes (see error in snapshot below). I am running a version of the toolbox that I downloaded 9/22/2020 in ArcGIS 10.7.
![image](https://user-images.githubusercontent.com/52179206/93933518-a59dbb00-fcd6-11ea-9909-7d7f34277bb4.png)

**Comment by LindaTedrow** [comment]
Two things to check:

  1.  Open ArcMap & drop the “topology” layer in,  it will ask do you want other layers – yes – this will show errors that need to be fixed.
  2.  Do you have annotations?  The validation code does not allow in the GeologicMap feature dataset.

Linda

**Comment by ethoms-usgs** [comment]
Tracey,
I think this has to do with em-dashes not being part of the ascii character set. Have you tried the Pro version of the tool? All strings in Python 3 are encoded as unicode by default so it's much smarter about non-ascii characters.

**Comment by tfelger** [comment]
Evan,
You are correct, that this gdb has em-dashes. I am able to run an older version of the tool successfully on the database, but wanted to try the new version, which has info about the GeMS compliancy levels. I tried the Pro version (downloaded today) as you suggested. It crashes and gives me an error about missing fields (see snapshot below), but it does produce some output.

![image](https://user-images.githubusercontent.com/52179206/93949605-ece77400-fcf5-11ea-95a9-07bd6776f9bd.png)

**Comment by ethoms-usgs** [comment]
The cursor set up near the line that throws that error is looking for the field 'MapUnit' and sorting the rows on 'HierarchyKey'. Are your field names in lowercase?

**Comment by tfelger** [comment]
The DMU table was missing 'HierarchyKey' and some other required fields. I loaded the data from the table with the missing fields into a copy that had all of the fields, and now the ArcPro version of the script runs to completion with no errors.

Thank you!

**Comment by ethoms-usgs** [comment]
Ok, great! 
The tool ought to have a graceful way to exit from that...

Where are the em-dashes in your gdb? I can add them to a gdb and try to fix the encoding bug you brought up in this issue (or you can send me your gdb).

**Comment by tfelger** [comment]
They are in the Type field. Here is an example value:
Contact—Identity and existence certain, location accurate

**Comment by rhaugerud** [comment]
I've modified Validate Database to better handle special chars--but am not sure that I've caught all instances where it could be a problem.
