### ISSUE TITLE
Level 3 Compliance -- missing or mis-defined elements

### ISSUE THREAD

**Issue by LindaTedrow** [usgs/gems-tools-arcmap#50]
Level 3 errors
Missing or mis-defined fields
    MapUnitPolys could not get field list. Fields not checked.
    ContactsAndFaults could not get field list. Fields not checked.
    CartographicLines could not get field list. Fields not checked.
    MapUnitPolys could not get field list. Fields not checked.
    CartographicLines could not get field list. Fields not checked.
    ContactsAndFaults could not get field list. Fields not checked.

In comparing fields to GeMS -- all fields appear correct and are set up as per the GeMS Geologic Map Schema.  

Why "could not get field list."?

**Comment by ethoms-usgs** [comment]
Linda,
If you could, open your copy of GeMS_ValidateDatabase_Arc10.py and add these edits.
Near the top, in the imports section add
`import traceback`

next go to line 542 where 
`except:`
is shown and change it to
```
except Exception:
    s = traceback.format_exc()
    arcpy.AddMessage("Error in function checkFieldDefinitions")
    arcpy.AddMessage(s)
```
and run the tool again. That should tell us which line exactly is throwing the error

**Comment by LindaTedrow** [comment]
Evan,
I see the problem.   And now I remember seeing this problem in the code.

The check fields routine does not put CSA or CSB before the fields when validating cross section FDS.
The error messages do not reflect which FDS has a problem.

I have notes from way back in July where I found the routine.

Will follow up tomorrow:

In the mean time, here is a snippet of messages that shows exactly where the issue is.
Both errors are for CrossSection and The Error should be CSB_MUP does not exist:

Messages
Executing: ValidateDatabase W:\DATABASE_MAPS\



  *   ;  ;  ;

  checking CrossSectionB for other stuff
  scanning CSBMapUnitPolys
Error in function checkFieldDefinitions
Traceback (most recent call last):
  File "W:\DATABASE_MAPS\GeMS_testing\gemsToolsOct2020\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 524, in checkFieldDefinitions
    fields = arcpy.ListFields(table)
  File "c:\program files (x86)\arcgis\desktop10.5\arcpy\arcpy\__init__.py", line 1138, in ListFields
    return gp.listFields(dataset, wild_card, field_type)
  File "c:\program files (x86)\arcgis\desktop10.5\arcpy\arcpy\geoprocessing\_base.py", line 346, in listFields
    self._gp.ListFields(*gp_fixargs(args, True)))
IOError: "MapUnitPolys" does not exist

  scanning CSBContactsAndFaults
Error in function checkFieldDefinitions
Traceback (most recent call last):
  File "W:\DATABASE_MAPS\GeMS_testing\gemsToolsOct2020\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 524, in checkFieldDefinitions
    fields = arcpy.ListFields(table)
  File "c:\program files (x86)\arcgis\desktop10.5\arcpy\arcpy\__init__.py", line 1138, in ListFields
    return gp.listFields(dataset, wild_card, field_type)
  File "c:\program files (x86)\arcgis\desktop10.5\arcpy\arcpy\geoprocessing\_base.py", line 346, in listFields
    self._gp.ListFields(*gp_fixargs(args, True)))
IOError: "ContactsAndFaults" does not exist



  *   ;  ;  ;


  writing database inventory
DONE
Completed script ValidateDatabase...
Succeeded at Tue Oct 13 17:01:51 2020 (Elapsed Time: 19 minutes 32 seconds)

**Comment by ethoms-usgs** [comment]
Excellent, Linda! Thank you for tracking that down. This will help. I will try to get to it soon.

**Comment by ethoms-usgs** [comment]
Linda,
Download the repo, or just Validate Geodatabase.py, and try again. I think I have it fixed. I found the same error you did when validating a gdb with cross sections, but got it to run with no errors after making the changes that are in this new version.

**Comment by LindaTedrow** [comment]
Evan,
That is great news.

I will give this a shot tomorrow morning.
Thank you very much,


Linda

Linda Tedrow
Idaho Geological Survey
University of Idaho
3rd Floor Morrill Hall
875 Perimeter Drive, MS 3014
Moscow, Id   83844-3014
(208) 885-1579

**Comment by LindaTedrow** [comment]
Evan,
Same results

Still came up with
Traceback (most recent call last):
  File "W:\Re_tool_stuff\GEMS_dev\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 1112, in <module>
    for row in cursor:
RuntimeError: An invalid SQL statement was used. [SELECT MapUnit FROM DescriptionOfMapUnits ORDER BY HierarchyKey]

Changed as before & fixed.

And again

Missing or mis-defined fields
    MapUnitPolys could not get field list. Fields not checked.
    ContactsAndFaults could not get field list. Fields not checked.
    CartographicLines could not get field list. Fields not checked.
    MapUnitPolys could not get field list. Fields not checked.
    CartographicLines could not get field list. Fields not checked.
    ContactsAndFaults could not get field list. Fields not checked.

Is there a way to include from which feature dataset the fields are checked?
Because, in this particular database I have included “extra” fds that would not have any of the above fields.

In the meantime, I will try on another database that does not yet have the extra.

Thank you for your help here.
Linda

**Comment by ethoms-usgs** [comment]
Hi Linda,
Could you confirm you have the most recent version of the script? Line 1112 in my version (and what you will see at https://github.com/usgs/gems-tools-arcmap/blob/master/Scripts/GeMS_ValidateDatabase_Arc10.py) is blank and I think the line throwing your error is down at 1126. 

And just to be clear, the edits I made are only an attempt to fix the issue of the fields in cross section feature classes getting properly inventoried. I don't yet have a guess about what is going on with the sql statement in the search cursor.

**Comment by LindaTedrow** [comment]
You are right
Line 112 is blank
1126 is for row in cursor:
1125 has the SearchCursor.

**Comment by LindaTedrow** [comment]
Evan,
We are moving along here.
Missing or mis-defined fields
    CSBMapUnitPolys, field MapUnitPolys_ID is missing
    CSBContactsAndFaults, field ContactsAndFaults_ID is missing
    CSBCartographicLines, field CartographicLines_ID is missing
    CSBCartographicLines, field DataSourceID is missing
    CSAMapUnitPolys, field MapUnitPolys_ID is missing
    CSACartographicLines, field CartographicLines_ID is missing
    CSACartographicLines, field DataSourceID is missing
    CSAContactsAndFaults, field ContactsAndFaults_ID is missing


CSBMapUnitPolys does have CSBMapUnitPolys_ID
CSBContactsAndFaults does have CSBContactsAndFaults_ID

CSACartographicLines & CSB CartographicLines do not have DataSourceID

All others (**_ID)  have the mentioned fields with CSX in front.


Linda

**Comment by ethoms-usgs** [comment]
Thank you, Linda. That makes sense. I think I can't get to this for a few days at this point, but I will let you know.

**Comment by LindaTedrow** [comment]
Evan,

No problem on the few days.

However, of note, to get last error message set I had to remove my location maps that do not have all the GeMS required fields, symbol, type, nor the typical layers.

  1.  A state outline and polygon of map area
  2.  Adjacent quad boundaries & polygon of map area

I am wondering if these can be ignored by validation ?

Look forward to seeing how you recode this.

Thanks again,

Linda

Linda Tedrow
Idaho Geological Survey
University of Idaho

**Comment by ethoms-usgs** [comment]
That's too bad, any extra tables or fields ought to simply get inventoried and listed as extra, but they shouldn't throw any errors or break compliance.

**Comment by LindaTedrow** [comment]
That is what I thought, Maybe after we fix this first problem I will add back in and then see.

**Comment by ethoms-usgs** [comment]
Ok, Linda. Could you download the toolbox or just the tool script and try again? 
I think I have the discovery of _ID fields working correctly in cross section feature classes.

**Comment by LindaTedrow** [comment]
Evan,
Yes, I downloaded last night and the validation of components in the crosssections worked well.
It found a field I had missed in the cross section cartographic lines.
I fixed this and re-ran – and confirmed that the database including crosssections were in GeMS format.

Thank you.
Linda

**Comment by ethoms-usgs** [comment]
Great. 
I will close this issue then
