### ISSUE TITLE
Validate Database failure

### ISSUE THREAD

**Issue by hsnellen** [usgs/gems-tools-arcmap#51]
I edited my ncgmp09 database by importing the GeoMaterialsDict and adding two new fields (GeoMaterials and GeoMaterialsConfidence) to get my database GeMS compliant.  When I run the validate database on the toolbox I'm prompted with this error:

Traceback (most recent call last):
  File "C:\Users\hsnellen\Downloads\gems-tools-arcmap-master\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 978, in <module>
    checkGeoMaterialDict(inGdb)
  File "C:\Users\hsnellen\Downloads\gems-tools-arcmap-master\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 811, in checkGeoMaterialDict
    for row in cursor:
RuntimeError: A column was specified that does not exist.

Can someone help me troubleshoot?

**Comment by ethoms-usgs** [comment]
Where the tool is throwing an error, it is looking (line 810) for the fields 'GeoMaterial' and 'Definition' in the GeoMaterialDict table so it would seem one of those is missing or misspelled. CamelCase formatting shouldn't matter, but I could be wrong. Be sure you are checking the actual field name and not the alias, in case one was added at some point.

From the standard, pg 25:
![image](https://user-images.githubusercontent.com/5376315/99843955-d7889d80-2b1e-11eb-88f7-d8a592e84d2f.png)

**Comment by hsnellen** [comment]
That was it, it seems when I imported the GeoMaterialDict into my database, it cut off the last letter in every field.
Thank you!

**Comment by ethoms-usgs** [comment]
Ok! Great. 
Where you, perhaps, importing the table from a dbf file? Those have a 9 character limit on field names.

**Comment by hsnellen** [comment]
Yes I was, I was not aware of the character limit.  That explains it.

**Comment by ethoms-usgs** [comment]
Ok, good to know. Thanks.
