### ISSUE TITLE
Issue with FGDC metadata, step 2

### ISSUE THREAD

**Issue by cgutierrez-01** [usgs/gems-tools-arcmap#53]
I have noticed an issue with the FGDC metadata, step 2 tool. All database elements are identified as non-spatial tables in the output xml files. The feature dataset and feature class elements are not being correctly identified (examples below). Any assistance with this issue will be greatly appreciated.

![image](https://user-images.githubusercontent.com/59892904/102643861-c2e6f780-4114-11eb-94fd-06b4a8d6438b.png)

**Comment by cgutierrez-01** [comment]
Sorry, the example text from the xml file did not retain its formatting in the previous post. 

![image](https://user-images.githubusercontent.com/59892904/102643861-c2e6f780-4114-11eb-94fd-06b4a8d6438b.png)

**Comment by ethoms-usgs** [comment]
Thanks for logging this, Carlos. I can't say for sure when I can take a closer look, but it is in the queue.

**Comment by cgutierrez-01** [comment]
Thanks, Evan! No rush, take your time. I appreciate the help, as always.

**Comment by ethoms-usgs** [comment]
I just posted a new version with a fix. It was the result of a simple typo. 
I ran it and got the expected results, but please let us know if this solves the problem for you.

**Comment by cgutierrez-01** [comment]
Thanks for the update, Evan. The tool is now working as expected. I really appreciate the fix!
