### ISSUE TITLE
Validate Database tool fails on syntax error

### ISSUE THREAD

**Issue by cgutierrez-01** [usgs/gems-tools-arcmap#55]
The latest version of the Validate Database tool (GeMS_ValidateDatabase_Arc10.py, version of 13 January 2021) is failing and reporting a syntax error in GeMS_Definition.py:

Executing: ValidateDatabase D:\Temp\GeMS\test\ValidateToolTest\GAM_15_El_Centro.gdb D:\Temp\GeMS\test\ValidateToolTest\validate_20210115 false false
Start Time: Tue Jan 19 10:04:40 2021
Running script ValidateDatabase...
Failed script ValidateDatabase...

Traceback (most recent call last):
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-master_20210115\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 30, in <module>
    from GeMS_Definition import *
  File "G:\CGS\GM_Work\Arcwork\ArcGIS_Files\GeMS\test\cg_testing\gems-tools-arcmap-master_20210115\gems-tools-arcmap-master\Scripts\GeMS_Definition.py", line 9
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

Failed to execute (ValidateDatabase).
Failed at Tue Jan 19 10:04:40 2021 (Elapsed Time: 0.06 seconds)

**Comment by rhaugerud** [comment]
Fixed. Apparently GeMS_Definition.py had last been edited using an editor that inserted some non-Pythonic lines.  

IF you re-download the repo (or just GeMS_Definition.py) you will get GeMS_Definition.py version of 19 January 2021. All should be good.

**Comment by cgutierrez-01** [comment]
Thanks, Ralph! I appreciate the quick response. Yeah, I thought those lines looked suspicious and definitely "non-Pythonic".

-Carlos

**Comment by cgutierrez-01** [comment]
Hi Ralph,

I guess I should have tested the tool before I responded. Now when I run the Validate Database tool, I get a new error message:

Executing: ValidateDatabase2 D:\Temp\GeMS\test\ValidateToolTest\GAM_15_El_Centro.gdb D:\Temp\GeMS\test\ValidateToolTest\validate_20210119 false false true
Start Time: Tue Jan 19 11:59:54 2021
ERROR 000576: Script associated with this tool does not exist.
Failed to execute (ValidateDatabase2).
Failed at Tue Jan 19 11:59:54 2021 (Elapsed Time: 0.00 seconds)

When I check the script properties, the Source tab specifies the following Script File:
D:\Temp\GeMS\gems-tools-arcmap-master_20210119\gems-tools-arcmap-master-OLD\Scripts\GeMS_ValidateDatabase_Arc10.py

The folder named "gems-tools-arcmap-master" has "-OLD" appended, which causes the tool to fail (folder does not exist). If I remove the "-OLD" the tool runs successfully. Not sure why this happened, or if it will affect other users, but I thought I would let you know.

Thanks,
Carlos

**Comment by rhaugerud** [comment]
Carlos-

Sorry about all this. I _think_ I
ve got it fixed now.  If you would be willing to re-download the toolbox and check me, I'd very much appreciate it.

cheers,

Ralph
________________________________

**Comment by cgutierrez-01** [comment]
Hi Ralph,

No worries, I am happy to assist. I just re-downloaded the toolbox and the Validate Database tool is functioning normally. Thanks again for responding so quickly and thanks also for your recent improvements to the tool. The removal of unused items from the Glossary and DataSources table is a huge time saver.

All the best,
Carlos

**Comment by rhaugerud** [comment]
Thanks for checking!
________________________________
