### ISSUE TITLE
Validate Database tool error

### ISSUE THREAD

**Issue by iseelye** [usgs/gems-tools-arcmap#56]
I am trying to run the Validate Database tool on a GeMS database, using the tools dated 2021-02-02. But every time I run it I get the error below. I know nothing of coding, but reading that it seems to think that there is an edit session in progress. But I have doubled checked and there is no edit session in progress on that database. I was able to successfully run the Validate Database tool from the toolbox dated 2020-10-07. So why is this new version not working?
Thank you,
Irene

![image](https://user-images.githubusercontent.com/78765070/107288170-dd07cc80-6a17-11eb-87a7-192b6333c528.png)

**Comment by ethoms-usgs** [comment]
The check for an edit session is only meant to print a warning message if one is found to be active. It won't crash the whole script.

Where the tool is failing, at line ```row = next(rows)```, seems to indicate that it can't create an iterable ```rows``` object. I won't get into the details of this, but does your gdb have either:

1. a GeoMaterialDict table with the field GeoMaterial or
2. a MapUnitPolys feature class (with at least 2 rows) in a GeologicMap feature dataset with the field MapUnit?

Either of those conditions need to be met in order for the editSessionActive function to be able to create a ```rows``` object. Check for that and us know.

**Comment by iseelye** [comment]
Thank you for the quick reply! 
1- yes it has a GeoMaterialDict table with the GeoMaterial field. It is currently empty though, does that matter?
2- yes it does have a MapUnitPolys feature class within the GeologicMap feature dataset that has 408 polygons in it, and the MapUnit field populated.

**Comment by ethoms-usgs** [comment]
Ok, I think what's happening is that since the GeoMaterialDict exists, the script also assumes it is not empty. I didn't notice that requirement the first time I looked at the code, sorry.  
Can you copy a full one in and try again?

**Comment by iseelye** [comment]
I would if I could. We have just started using GeMS and this is one of the first databases we are working on. I have not worked on the GeoMaterialsDict table yet, so I don't have one to copy into it. Still learning what it needs to be. Since those are the only errors, I hope that once I have a chance to sort that out it will all work fine. It is interesting to me that the old tool runs fine, but the new one doesn't, you must have made major changes.

**Comment by ethoms-usgs** [comment]
Ah! GeoMaterialDict is a controlled table that should always have the same contents. Run the Create Database tool to make a dummy gdb. It will contain the table and you can copy and paste.

**Comment by iseelye** [comment]
That worked great thank you, the tool now runs just fine. Problem solved, now i know what to watch out for. Thanks.
