### ISSUE TITLE
Problem with MakePolys

### ISSUE THREAD

**Issue by ethoms-usgs** [usgs/gems-tools-arcmap#59]
On behalf of Stephanie Dudash:
*********************************************************

Hello, I'm trying to make polygons (with latest version of GeMS tools) and I get this error.  Do you have any suggestions?

Executing: MakePolys C:\Users\sdudash\Documents\SAFSOC\_Dudash\PMF\GISdata\SunfairGeologicMap.gdb\SunfairQuad false # C:\Users\sdudash\Documents\SAFSOC\_Dudash\PMF\GISdata\SunfairGeologicMap.gdb\SunfairQuad\MapUnitPoints
Start Time: Tue Mar  2 11:23:05 2021
Running script MakePolys...
GeMS_MakePolys3_Arc10.py, version of 5 January 2018
  Saving selected layers and removing them from current data frame
    looking for C:\Users\sdudash\Documents\SAFSOC\_Dudash\PMF\GISdata\SunfairGeologicMap.gdb\SunfairQuad\MapUnitPolys
Failed script MakePolys...

Traceback (most recent call last):
  File "C:\Users\sdudash\Documents\WORK\GeMS\LatestGeMSTools\gems-tools-arcmap-1.5.1\Scripts\GeMS_MakePolys3_Arc10.py", line 139, in <module>
    arcpy.SaveToLayerFile_management(lyr, lyrPath, "RELATIVE")
  File "c:\arcgis\desktop10.8\arcpy\arcpy\management.py", line 7709, in SaveToLayerFile
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000840: The value is not a Layer.
Failed to execute (SaveToLayerFile).

Failed to execute (MakePolys).
Failed at Tue Mar  2 11:23:07 2021 (Elapsed Time: 1.88 seconds)

**Comment by BenjiDa** [comment]
Zenon and I have been having this same problem.

**Comment by ethoms-usgs** [comment]
Aha! I couldn't raise that same error until I joined MapUnitPolys to DescriptionOfMapUnits. We can look into scripting around that, but in the meantime I think the workaround is to avoid joins.

**Comment by ethoms-usgs** [comment]
Stephanie ran into the error when trying to create MapUnitPolys for the first time, rather than, as I was doing, running the tool after edits to ContactsAndFaults to rebuild existing polygons. Is that your situation, Ben? If so, use Feature to Polygon first and we'll look at the code to make it sure it will build from scratch.

**Comment by BenjiDa** [comment]
I was also building for the first time, but had the same error when running a second time. Got around it using Feature to Polygon without concealed lines, of course this is not the ideal solution.

**Comment by rhaugerud** [comment]
The MakePolys script--perhaps inadvisably--assumes that it is being run from an ArcMap session in which the map composition has a MapUnitPolys layer that references the MapUnitPolys feature class.

The script deletes the MapUnitPolys feature class and and rebuilds it while saving any symbolization belonging to the MapUnitPolys layer. To do this, it writes the MapUnitPolys layer to a layer file, removes the MapUnitPolys layer from the map composition. Then deletes the MapUnitPolys feature class, rebuilds it (where the meat of the script is), and adds the saved MapUnitPolys layer back into the map composition.

Some checking for the existence of a MapUnit polys layer, with a useful error message when it's not found, might be a good idea. 🙂
________________________________

**Comment by zvalin** [comment]
I'm having a different problem with making polygons using the GeMS tool. The polygons get built, but I'm not able to label the map units using a label point feature. I've tried testing it with different maps, but the polygons never get labeled.

**Comment by ethoms-usgs** [comment]
Zenon, can you describe this more? When you say "the polygons never get labeled." are you saying that labels don't visually appear in the map to label polygons or are you saying that the attributes from MapUnitPoints don't get transferred to MapUnitPolys? The former is a layer property that the tool does not set and the latter is a problem we would have to look into.

**Comment by zvalin** [comment]
The attributes from MapUnitPoints don't get transferred to MapUnitPolys.

**Comment by ethoms-usgs** [comment]
Ok, thanks for clarifying. Noted.

**Comment by LindaTedrow** [comment]
Evan,
We, (Idaho) IGS, generally use identity or a spatial join and then a temporary join to attribute MapUnitPolys from a point file.
Is there another way?
Linda

**Comment by sdudash** [comment]
Ralph, maybe I'm missing something? I will create my geology by lines and points and then make a map unit polygon feature class, but I don't make the polygons until later in my process.  So, I'm a little confused to this statement "has a MapUnitPolys layer that references the MapUnitPolys feature class".  At what point are you making a MapUnitPoly feature class and layer and how are you making it.  Are you using the ArcMap tool FeatureToPolygon? Thanks

**Comment by rhaugerud** [comment]
MapUnitPolys may be an empty feature class made by the Create New Database script.  If you don't have it, you could make a scratch database with the Create New Database tool and then copy the newly-created MapUnitPolys into your working database.

The layer is the row in the Table of Contents of the map composition, which ArcMap by default names "MapUnitPolys" when you add that feature class to the map composition.

________________________________

**Comment by rhaugerud** [comment]
Stephanie-

Let me know if you want to talk about this.  I could use some help in assuming less and documenting more.

Ralph
________________________________

**Comment by rhaugerud** [comment]
Re Stephanie's bug:

MakePolys throws a bunch of label points into the FeatureToPolygon pot.  Apparently this ArcMap tool has no guarantees as to which​ of any possible multiple label points are used to attribute the newly-made polygons, which is much of the reason for all of the error- and edit- feature classes generate by the MakePolys tool.

MapUnitPolys uses two sets of label points: those you give it, if any, and another set generated by intersecting the centroids of newl-created polygons with any existing MapUnitPolys.  In your case, where MapUnitPolys was empty, all of these 2nd set of label points have MapUnit = null. 

MapUnitPolys calls arcpy.FeatureToPolygon_management, which apparently has no guarantees as to which​ of any possible multiple label points are used to attribute the newly-made polygons. In your case, only those with MapUnit = null were being used, thus the newly-made polys with MapUnit = null.

Points with MapUnit = '' were already being deleted from the aggregate label points. I've added code to delete any label points with MapUnit = null.  

Zenon, perhaps this fixes your problem.

**Comment by sdudash** [comment]
Just wanted to update: Ralph seems to have fixed the bug as I was able to get the tool to work!

**Comment by ethoms-usgs** [comment]
Ok! I will close the issue. We can open it again if someone still has trouble.
