### ISSUE TITLE
Topology check tool crashes

### ISSUE THREAD

**Issue by tfelger** [usgs/gems-tools-arcmap#60]
I tried the new version of the topology check tool and it crashes with the following error:

Executing: TopologyCheck C:\Data\ProjectData\LOCO\Blythe100k\Blythe100k_RevisedAfterPubsEdit\BL100k_20201209.gdb\GeologicMap 000-000-002-000-000
Start Time: Fri Mar  5 09:45:07 2021
Running script TopologyCheck...
Failed script TopologyCheck...

Traceback (most recent call last):
  File "C:\Data\ProjectData\GIS\DataModels\GeMS\ArcMap\gems-tools-arcmap-master_20210304\Scripts\GeMS_TopologyCheck_Arc10.py", line 48, in <module>
    checkVersion(versionString, rawurl, 'gems-tools-arcmap')
NameError: name 'checkVersion' is not defined

Failed to execute (TopologyCheck).
Failed at Fri Mar  5 09:45:07 2021 (Elapsed Time: 0.06 seconds)

**Comment by RosieUtah** [comment]
Someone here (Utah Survey) recently tried the check topo tool also and got the error below when the tool started running on the "faults" feature class. The assumption was that the fields weren't fully attributed but that shouldn't matter, should it?

GEMsConversionTools\gems-tools-arcmap-master\gems-tools-arcmap-master\Scripts\GeMS_TopologyCheck_Arc10.py", line 633, in validateCafNodes
    if isFault(arcs[0][3]):
  File "G:\My Drive\2021\Statemap\GEMsConversionTools\gems-tools-arcmap-master\gems-tools-arcmap-master\Scripts\GeMS_utilityFunctions.py", line 136, in isFault
    **if lType.upper().find('FAULT') > -1:
AttributeError: 'NoneType' object has no attribute 'upper'**

**Comment by rhaugerud** [comment]
I agree with you, it looks like the tool encountered a ContactsAndFaults line with a null value for Type.

The Topology Check tool treats contacts and faults differently: faults can dangle, contacts mostly should not; the directionality (To-From) of contacts is rarely significant whereas the directionality of faults commonly is (it describes which side of the fault is upper plate and thus ornamented); faults can have the same map unit on both sides, whereas contacts should not.   So I think this is desired behavior.
________________________________

**Comment by RosieUtah** [comment]
Thanks for clarifying Ralph! 

Tracey, I'm sorry I can't help you with your error (obviously, I'm a newbie at this stuff). Were you able to fix it?

**Comment by rhaugerud** [comment]
Tracey, thanks for pointing out this bug. It's fixed, I think.
