### ISSUE TITLE
Failure to use AttributeByKeyValues successfully

### ISSUE THREAD

**Issue by RosieUtah** [usgs/gems-tools-arcmap#61]
Hi all,

I'm testing out the AttributeByKeyValues tool and I'm having difficulty getting it to work. I created a new GDB with the latest toolbox (from today). It only has a few feature classes in it and I only added one feature to the CartographicLines feature class -- a cross section. I populated the "Symbol" field to use as my Key field. This is my first question -- is it okay to NOT use LType or SType?

Here's what my KeyValueFile TXT file looks like:

**CartographicLines
Symbol|Type|Label
Cross section, A-A'|Cross section|A-A'**

And here's the message I'm getting:

**Executing: AttributeByKeyValues "G:\Shared drives\UGS_Editorial_GIS\GeMS\Training\20210225_GIS_1\uGeMS_GoshenPass.gdb" "G:\Shared drives\UGS_Editorial_GIS\GeMS\Training\20210225_GIS_1\KeyValueFile_GoshenPass_delimTXT_test.txt" true
Start Time: Thu Mar 11 17:37:07 2021
Running script AttributeByKeyValues...
  GeMS_AttributeByKeyValues_Arc10.py, version of 7 March 2021
Forcing the overwriting of existing fields
[u'MapUnitPolys', u'ContactsAndFaults', u'CartographicLines', u'GenericPoints']
['\xef\xbb\xbfCartographicLines']
﻿CartographicLines
Failed script AttributeByKeyValues...

Traceback (most recent call last):
  File "G:\Shared drives\UGS_GeMS\GeMS_Reference\Scripts\Toolset\gems-tools-arcmap-master\Scripts\GeMS_AttributeByKeyValues_Arc10.py", line 89, in <module>
    addMsgAndPrint('  ' + fClass + ' not in ' + gdb + "\\" + finalfds)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 2: ordinal not in range(128)

Failed to execute (AttributeByKeyValues).
Failed at Thu Mar 11 17:37:21 2021 (Elapsed Time: 13.50 seconds)**

I've run the script several times with different feature classes and slight changes to the Key Value File and now, this new GDB. I've tried it with the overwrite option on and off, in ArcCatalog, in ArcMap editing, and in ArcMap without an edit session started. I'm afraid I'm missing a requirement for this script but am not sure what it is. 

Any guidance would be great! Thanks for your help!

**Comment by ethoms-usgs** [comment]
Hi Rosemary,
First, the name of the field with the un-parsed feature attributes is meant to be something not defined by GeMS, such as the examples of LTYPE, PTYPE, or STYPE. Using Symbol is odd to me unless you are also using a style file with a symbol called 'Cross section, A-A'. That said, I think the tool should still work. It should still read the content of Symbol and then populate the other two fields based on the value found there.

Second, it looks to me like the tool is parsing your KeyValue text file and finding CartographicLines but then is not finding that feature class in the gdb Are those two names exactly alike?

**Comment by RosieUtah** [comment]
Hi and thanks for your help!

We are, indeed, using a style file with the symbol called "Cross section, A-A'" because it fits well with our already-existing schema. It'd be great if the tool will work without having to add another field like LTYPE, PTYPE, or STYPE. But we'll do what we have to do.

I hadn't noticed that second version of the Cartographic lines feature class; is that actually a feature class or some kind of data table or something? When I look at my GDB in Catalog, I only see one version of the feature class and it's called "CartographicLines" so I'm a bit bewildered. A screenshot of my GDB in ArcCatalog:

![image](https://user-images.githubusercontent.com/30906748/111225865-eef40680-85a5-11eb-9450-7ca4bb1694e5.png)

I thought it might have something to do with the fact that I'm working on the Google Drive (aka File Stream) so I copied all of my data (not the toolbox, mind you) over to my desktop and still get the following error:

```
Running script AttributeByKeyValues...
  GeMS_AttributeByKeyValues_Arc10.py, version of 7 March 2021
Forcing the overwriting of existing fields
[u'MapUnitPolys', u'ContactsAndFaults', u'GeologicLines', u'CartographicLines', u'MapUnitLines', u'MapUnitPoints', u'GenericPoints', u'OrientationPoints', u'CartographicPoints']
['\xef\xbb\xbfCartographicLines', '', '', '', '', '']
Failed script AttributeByKeyValues...

Traceback (most recent call last):
  File "G:\Shared drives\UGS_GeMS\GeMS_Reference\Scripts\Toolset\gems-tools-arcmap-master\Scripts\GeMS_AttributeByKeyValues_Arc10.py", line 104, in <module>
    if len(vals) <> numMFields:
NameError: name 'numMFields' is not defined

Failed to execute (AttributeByKeyValues).
Failed at Mon Mar 15 15:39:23 2021 (Elapsed Time: 8.24 seconds)
```

I wonder if it has something to do with how I've created my TXT file. I created everything in Excel and set my default delimiter to "pipe". Then, I saved the table as a CSV which was easily opened as a text document and saved. Is there a better process?

**Comment by ethoms-usgs** [comment]
Sorry! I just noticed that ```'\xef\xbb\xbfCartographicLines'``` is not part of the list above it of feature classes from the gdb. That is being reported during a listing of the names of feature classes found in the key values text file and, looking around a bit more, it looks like Excel has exported the CSV file as UTF8 with BOM (Byte Order Mark(s)) at the beginning of the file (the hex characters), which is making it difficult for the python print function to print the string to the screen. 

We should write code to find and accommodate this, but in the meantime, try exporting from Excel where you explicitly set the encoding to 'UTF-8'. About one-third down on [this](https://www.webtoffee.com/how-to-save-csv-excel-file-as-utf-8-encoded/) page is an explanation.

If that doesn't work, try re-creating the file from scratch in notepad or notepad++.

**Comment by ethoms-usgs** [comment]
I just re-created your key value text file in Excel and looked at the resulting encoding as reported by Notepad++ after three different exports:

1. Using Save As > CSV UTF-8 from the drop-down list resulted in a file with UTF-8 BOM encoding
2. Using Save As > CSV gave me a UTF-8 file with no BOM and 
3. Using Save As > More options > Tools > Web Options > Encoding > Save this document as > Unicode UTF-8 gave me a file in UTF-8  with no BOM.

So, the short explanation here is you should be able to use the second option (unless there is some kind of default setting that overrides that)

**Comment by RosieUtah** [comment]
Thanks again, it looks like that made a difference (I was using option 1). Now I'm getting a different error that reads as follows:

```
Executing: AttributeByKeyValues "G:\Shared drives\UGS_Editorial_GIS\GeMS\Training\20210225_GIS_1\uGeMS_M286DM_GoshenPass.gdb" "G:\Shared drives\UGS_Editorial_GIS\GeMS\Training\20210225_GIS_1\KeyValueFile_GoshenPass_delim_noBOMsTXT.txt" true
Start Time: Mon Mar 15 17:46:27 2021
Running script AttributeByKeyValues...
  GeMS_AttributeByKeyValues_Arc10.py, version of 7 March 2021
Forcing the overwriting of existing fields
[u'MapUnitPolys', u'ContactsAndFaults', u'GeologicLines', u'CartographicLines', u'MapUnitLines', u'MapUnitPoints', u'GenericPoints', u'OrientationPoints', u'CartographicPoints']
['CartographicLines', '', '', '', '', '']
Failed script AttributeByKeyValues...

Traceback (most recent call last):
  File "G:\Shared drives\UGS_GeMS\GeMS_Reference\Scripts\Toolset\gems-tools-arcmap-master\Scripts\GeMS_AttributeByKeyValues_Arc10.py", line 104, in <module>
    if len(vals) <> numMFields:
NameError: name 'numMFields' is not defined

Failed to execute (AttributeByKeyValues).
Failed at Mon Mar 15 17:46:38 2021 (Elapsed Time: 10.70 seconds)
```

I could be wrong but I think it's because my Excel to CSV to TXT added a bunch of extra pipes to make up for blank columns (for the feature classes that don't have as many fields). Is this some kind of default in Excel? Should I find and replace extra ones somehow? See my screen shot below:

![image](https://user-images.githubusercontent.com/30906748/111235745-e952ec80-85b6-11eb-886e-e0d3ae734fa4.png)

**Comment by RosieUtah** [comment]
I deleted the extra pipes at the end of the lines as well as between each feature class. I also discovered hundreds of extra lines at the end -- just 5 pipes row after row.

The script worked perfectly!!

However, I feel like I am missing something in the process of developing my KVF in Excel that makes it not create or produce these extra rows and pipes. Is there something I'm doing wrong? Is there a quick and easy fix or will it require a manual removal?

Thanks again for your help!

**Comment by ethoms-usgs** [comment]
If you are missing something, I don't think it's that much. You are finding the limitations of using Excel to edit a text file and I don't know Excel well enough to give you any suggestions. Personally, I would edit the file in a text editor. Notepad++ is my favorite.

Sounds like you are on your way. Can we close this issue?

**Comment by RosieUtah** [comment]
Sounds good. Thanks again for your help!
