### ISSUE TITLE
Point feature classes Null MapUnit field

### ISSUE THREAD

**Issue by chhalsted** [usgs/gems-tools-arcmap#69]
The ValidateDatabase tool is returning errors when I have GenericPoints (map and cross-section) that are outside the extent of the MapUnit polygons and have null MapUnit field values.  If I'm interpreting Table 20 in the GeMS standard correctly, this should be allowed.   Thanks

**Comment by ethoms-usgs** [comment]
Yes, so it should. It brings up the problem of checking that only those points outside of the polygon area have nulled MapUnits, but I will kick that down the road for now and change the definition for just that featureclass. 
The latest version, v1.6.4, has the change in it.

**Comment by chhalsted** [comment]
Thanks for the wicked quick response Evan.  
On a related note, I wasn't paying attention and posted this to the arcmap tools when I'm actually using the arcpro tools.  Do all the issues eventually get ported over to arcpro?  I don't envy you having to maintain 2 code bases!

**Comment by ethoms-usgs** [comment]
You are welcome. You are just lucky that I am looking at issues today!

No! the issues are completely separate between the two repos, but thank you for reminding me. I just made the same change over at the Pro repo.

**Comment by chhalsted** [comment]
Great, thanks.
