### ISSUE TITLE
Validate database crash

### ISSUE THREAD

**Issue by hsnellen** [usgs/gems-tools-arcmap#72]
I've been running one of my databases through the tool and it was working, but I've since made edits to the database to correct the GeMS errors.  Now when I run the same database through the tool, I get this error:
![image](https://user-images.githubusercontent.com/41085615/124005354-d6a9cb00-d98d-11eb-93b0-324551e88b2b.png)

I've downloaded the most up to date version of the tool, started with a fresh document, ran the tool through Catalog and same error.
Any ideas?

**Comment by ethoms-usgs** [comment]
The code is trying to write out a warning about a GeoMaterial value that can't be found in GeoMaterialDict but the value contains a non-ASCII-set character that isn't being decoded correctly. Did you add a GeoMaterial to the DMU that isn't in the dictionary?

**Comment by hsnellen** [comment]
### DescriptionOfMapUnits
- [ ] Missing DataSourceID

**Comment by hsnellen** [comment]
I just double checked and all terms that are in the GeoMaterials field in the DMU, are all present in the GeoMaterialDict.  
Not sure if this would affect it, but for the headings in the DMU there is nothing filled out in the GeoMaterials column. Could that cause issues?

**Comment by ethoms-usgs** [comment]
Hmm, no, nulls are ok in that table. 
As far as I can tell, the character code reported in the message \u201c refers to "left double quotation mark". Were the values in that field copied over from outside of ArcMap?

**Comment by hsnellen** [comment]
Ah that was it. I wasn't the one who filled out that portion but there was one GeoMaterials term, ""Made" or human-engineered land" that had a faulty character within the quotation. 
Thanks for solving this!
Just re-ran the tool and it's working again.

**Comment by ethoms-usgs** [comment]
Great! I will close this.
