### ISSUE TITLE
Translate to shapefile crash

### ISSUE THREAD

**Issue by hsnellen** [usgs/gems-tools-arcmap#75]
I'm trying to run the "Translate to shapefile" tool and get prompted with this error:
![image](https://user-images.githubusercontent.com/41085615/128561285-45b93e88-42fc-49f4-8005-ba8e606f95f8.png)
 I've downloaded the most recent version of the toolbox and attempted to run the tool in ArcCatalog not no luck.

**Comment by ethoms-usgs** [comment]
There was a typo! SearchCursor was misspelled. I have updated the script. Try v1.6.7

**Comment by hsnellen** [comment]
Okay I've downloaded the newest version of the toolbox and tried to use the same tool and received this error:
![image](https://user-images.githubusercontent.com/41085615/129099543-ad10a540-61c8-4cb2-9de7-4f630c0d3c1c.png)

I did this in both ArcMap and Pro.

**Comment by hsnellen** [comment]
Alright downloaded it, and gives this error now:
![image](https://user-images.githubusercontent.com/41085615/129109478-266f297e-b517-411f-9be8-786f14534921.png)

I can send the database too if that would help?

**Comment by ethoms-usgs** [comment]
Is there anything in StandardLithology?

**Comment by hsnellen** [comment]
No it's empty, in our databases we have some legacy tables that need to be present in order for us to be able to use our toolbar to open the gdb. 
I could make a copy of this database though and delete that table if you're thinking it could be my problem.

**Comment by ethoms-usgs** [comment]
Yes, please try that. I think that will be informative.

**Comment by hsnellen** [comment]
Deleted that table, and now the tool runs just fine!
Thanks for helping me troubleshoot.

**Comment by ethoms-usgs** [comment]
Great! I have started a Known Issues page at the Wiki to log errors like this. Hopefully fixing them will become enhancements some day.
