### ISSUE TITLE
Topology Check Tool crashes

### ISSUE THREAD

**Issue by tfelger** [usgs/gems-tools-arcmap#76]
See error below:
Executing: TopologyCheck C:\Data\ProjectData\LOCO\Blythe100k\Blythe100k-GeMS\Blythe100k-publication\Blythe100k-database\BL100k_20210811.gdb\GeologicMap 000-000-001-000-000
Start Time: Wed Aug 11 14:32:34 2021
Running script TopologyCheck...
GeMS_TopologyCheck_Arc10.py, version of 8 March 2021
Making directory C:\Data\ProjectData\LOCO\Blythe100k\Blythe100k-GeMS\Blythe100k-publication\Blythe100k-database\BL100k_20210811_Topology
 
Writing to C:\Data\ProjectData\LOCO\Blythe100k\Blythe100k-GeMS\Blythe100k-publication\Blythe100k-database\BL100k_20210811_Topology\BL100k_20210811_TopologyCheck.gdb. Note that nodes within 0.002 map units of each other are considered identical.
 
Checking topology of GeologicMap
  creating topology GeologicMap_topology
  adding rules to topology:
    Must Not Overlap (Line)
    Must Not Self-Overlap (Line)
    Must Not Self-Intersect (Line)
    Must Be Single Part (Line)
    Must Not Overlap (Area)
    Must Not Have Gaps (Area)
    Boundary Must Be Covered By (Area-Line)
  validating topology
  exporting topology errors
    0 rows in errors_GeologicMapTopology_point
    1 rows in errors_GeologicMapTopology_line
    0 rows in errors_GeologicMapTopology_poly
Planarizing ContactsAndFaults and getting segment endpoints
  planarizing caf
  IDENTITYing caf with mup
  deleting extra fields
  adding StartAzimuth and EndAzimuth
  converting line ends to points
  adding POINT_X and POINT_Y
Sorting segment endpoints into nodes
  7144 endpoints
  2511 nodes
Processing nodes
  165 1-arc nodes
  304 2-arc nodes
  1805 3-arc nodes
  229 4-arc nodes
  8 5+ arc nodes
Bad nodes: 74
Fault-flip nodes: 6
Missing concealed-arc nodes: 1155
ConnectFIDs: 2166
Building feature class errors__BadNodes
  inserting points into errors__BadNodes
Failed script TopologyCheck...

Traceback (most recent call last):
  File "C:\Data\ProjectData\GIS\DataModels\GeMS\ArcMap\gems-tools-arcmap-master_20210720\Scripts\GeMS_TopologyCheck_Arc10.py", line 810, in <module>
    insertNodes(badNodesFC,badNodes)
  File "C:\Data\ProjectData\GIS\DataModels\GeMS\ArcMap\gems-tools-arcmap-master_20210720\Scripts\GeMS_TopologyCheck_Arc10.py", line 377, in insertNodes
    cursor.insertRow(row)
RuntimeError: The row contains a bad value. [ArcTypes]

Failed to execute (TopologyCheck).
Failed at Wed Aug 11 14:33:33 2021 (Elapsed Time: 59.61 seconds)

**Comment by ethoms-usgs** [comment]
Tracey,
Shot in the dark here, but it could be that the value being written to the field called ArcTypes is too long. Try this, open the script file and find line 188. Change it to 
```arcpy.AddField_management(fdfc,f,'TEXT','','',500)``` or something longer than 100.

**Comment by tfelger** [comment]
Hi Evan, That solved the problem - thanks!

**Comment by ethoms-usgs** [comment]
Great! good to know. I just published a new version with the change. Your modified script will work except it will now throw the  'obsolete version' warning unless you update versionString to ```'GeMS_TopologyCheck_Arc10.py, version of 13 August 2021'```

or download the latest.
