### ISSUE TITLE
Create New Database tool generates two primary key fields in attributes for cross sections

### ISSUE THREAD

**Issue by jamato-WSGS** [usgs/gems-tools-arcmap#82]
Using GeMS Tools for Arc10.5 2020-06-07

Create New Database tool generates cross section datasets which contain ContactAndFaults, MapUnitPolys, and OrientationPoints feature classes that contain two ID fields in the attributes (i.e. "CSAContactsAndFaults_ID" and "ContactsAndFaults_ID" + CSAMapUnitPolys_ID and MapUnitPolys_ID + CSAOrientationPoints_ID" and "OrientationPoints_ID) .. assuming we only need one primary key? Not finding anything in the GeMS publication that discusses having two ID fields. 

I ran into this recently working on a map project with a previously created GeMS geodatabase, I assumed it was an internal mistake so I deleted/edited the fields to only have 1 primary key, it resulted in a "mis-defined fields" error with running the validation script. I recently just ran the tool, and noticed that the error is being generated from the script. My assumption is we should be using the CSAContactsAndFaults_ID field as the primary key and the ContactsAndFaults_ID field should be omitted?

James Amato
Map Editor & Geospatial Technical Principal
Wyoming State Geological Survey
james.amato@wyo.gov
307-766-2286 ext.250

**Comment by ethoms-usgs** [comment]
Hi James,
Could you verify you still get this error with the latest version of the tool ("GeMS_CreateDatabase_Arc10.py, version of 23 December 2020")? I just created a couple geodatabases setting extra cross sections and the OrientationPoints fc and didn't end up with any extra _ID fields, only the ones expected. Likewise, the validation tool didn't report errors regarding those fields.

**Comment by jamato-WSGS** [comment]
I just download the latest version and did not experience the problem. Must have just been a bug in Arc10.5 2020-06-07. My apologies, I didn't realize I wasn't using an outdated version. Thanks Ethan
